# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149697yabGWNdR7gY-aZzjDnVePoUKiA0
"""

import streamlit as st
import random

# --- 1. Music Data (UNCHANGED) ---
MUSIC_DATA = {
    "City Pop": [
        "https://www.youtube.com/embed/TBLZSXwfjbE",
        "https://www.youtube.com/embed/p9dRg8yQ2DY",
    ],
    "Jazz HipHop": [
        "https://www.youtube.com/embed/dtVwR4uMnfg",
        "https://www.youtube.com/embed/OIvGy0wM5_s",
    ],
    "Study Focus": [
        "https://www.youtube.com/embed/219beSEfbqA",
        "https://www.youtube.com/embed/_Q8Ih2SW-TE",
    ],
    "Ambient Jazz": [
        "https://www.youtube.com/embed/CfPxlb8-ZQ0",
        "https://www.youtube.com/embed/o26qoCYLdS8",
    ]
}

# --- 2. Core Recommendation Logic (UNCHANGED) ---
def recommend_music(mood_score, location):
    """Returns a recommended music genre based on the mood score and location key."""

    if mood_score >= 8:
        genre = "City Pop"
    elif mood_score >= 5:
        genre = "Jazz HipHop"
    else:
        genre = "Ambient Jazz"

    if location in ["Commute"]:
        genre = "City Pop" if mood_score >= 5 else "Jazz HipHop"
    elif location in ["Study", "Work"]:
        genre = "Study Focus" if mood_score >= 6 else "Jazz HipHop"
    elif location == "Park":
        genre = "City Pop" if mood_score >= 6 else "Jazz HipHop"
    elif location == "Home":
        genre = "Ambient Jazz" if mood_score < 6 else "Jazz HipHop"

    return genre

# --- 3. Streamlit UI (Pure Python for UI/Style) ---

st.set_page_config(page_title="Kawaii Jukebox", layout="wide")

# --- CUSTOM CSS FOR KAWAII MINIMALISM & CONTRAST FIX ---
st.markdown("""
    <style>
    /* 1. FONT AND BACKGROUND (Forced Cursive/Handwriting Font) */

    /* 强制使用设备上最可爱的字体族 (cursive)，并加大字号来强调 */
    .stApp {
        background-color: #284d3c; /* RETAINED: Christmas Deep Green */
        color: #FFFFFF; /* FIXED: Bright White Text for High Contrast */
        font-family: cursive; /* *** FONT CHANGE: FORCED CURSIVE *** */
        font-size: 1.4em; /* 强制加大字号，让字体看起来更突出和可爱 */
    }
    h1, h2, h3 {
        color: #FF69B4; /* Hot Pink/Magenta Accent for Headers */
        font-family: cursive;
        font-weight: 900; /* 加粗 */
        text-shadow: 2px 2px 3px rgba(0, 0, 0, 0.6); /* 增强阴影，让标题在深色背景上更跳脱 */
    }

    /* 2. CUSTOM RADIO BUTTON (Cute Checkmark) */

    [data-testid="stForm"] label, [data-testid="stRadio"] label {
        color: #FFFFFF;
        font-size: 1.0em; /* 保持单选按钮选项文本可读 */
    }

    /* Checkmark dot when SELECTED */
    [data-testid="stRadio"] input[type="radio"]:checked + div::before {
        background-color: #FF69B4 !important;
        border: 4px solid #FFFFFF !important;
    }
    /* Checkmark dot when NOT selected */
    [data-testid="stRadio"] input[type="radio"] + div::before {
        background-color: #FFFFFF !important;
        border: 2px solid #FF69B4 !important;
    }

    /* 3. BUTTON STYLE (Cute Pink) */
    .stButton>button {
        background-color: #FF69B4;
        color: #FFFFFF;
        border: 2px solid #FFC0CB;
        font-weight: 700;
        border-radius: 12px;
        font-family: cursive; /* 按钮文本也使用手写体 */
        font-size: 1.2em;
    }
    .stButton>button:hover {
        background-color: #e65a9e;
    }

    /* 4. Cleanup and Info Boxes */
    [data-testid="stInfo"] {
        background-color: rgba(255, 105, 180, 0.2);
        color: #FFFFFF !important;
        border-left: 5px solid #FF69B4 !important;
        font-size: 1.1em;
        font-family: cursive;
    }

    /* 5. SNOWFALL STYLES (Cute Christmas Vibe) */
    @keyframes snowfall {
        0% {top: -10%;}
        100% {top: 100%;}
    }
    .snowflake {
        color: #FFFFFF; /* White Snow/Hearts for visibility */
        font-size: 1.2em;
        position: fixed;
        z-index: 9999;
        user-select: none;
        pointer-events: none;
        animation-name: snowfall;
        animation-timing-function: linear;
        animation-iteration-count: infinite;
    }
    /* ... 保持雪花动画效果 ... */
    .snowflake:nth-child(1) { left: 5%; font-size: 1.5em; animation-duration: 10s; animation-delay: 0s; }
    .snowflake:nth-child(2) { left: 15%; font-size: 1.0em; animation-duration: 15s; animation-delay: 2s; }
    .snowflake:nth-child(3) { left: 25%; font-size: 1.8em; animation-duration: 12s; animation-delay: 4s; }
    .snowflake:nth-child(4) { left: 40%; font-size: 1.3em; animation-duration: 18s; animation-delay: 6s; }
    .snowflake:nth-child(5) { left: 60%; font-size: 1.6em; animation-duration: 11s; animation-delay: 8s; }
    .snowflake:nth-child(6) { left: 80%; font-size: 1.1em; animation-duration: 16s; animation-delay: 10s; }
    </style>
""", unsafe_allow_html=True)

# --- SNOWFALL HTML (Hearts, Stars, Tree, Ribbons) ---
st.markdown("""
    <div class="snowflake">💖</div>
    <div class="snowflake">⭐</div>
    <div class="snowflake">🎄</div>
    <div class="snowflake">🎀</div>
    <div class="snowflake">❄️</div>
    <div class="snowflake">⭐</div>
""", unsafe_allow_html=True)

# --- APP TITLE (CLEANED: NO EMOJIS) ---
st.title("Mood Jukebox")
st.markdown("---")


# --- UI Controls (Creative Input) ---
col1, col2 = st.columns(2)

with col1:
    # CLEANED: NO EMOJIS IN HEADER
    st.markdown("### Your Current Vibe")

    mood_choice = st.radio(
        # CLEANED: No brackets or lengthy explanation
        label="Select the feeling that matches your mood:",
        options=[
            "Sparkly (High Energy)",
            "Calm (Medium Focus)",
            "Cozy (Low Chill)"
        ],
        index=1
    )

    if "Sparkly" in mood_choice:
        mood_score = 9
    elif "Calm" in mood_choice:
        mood_score = 6
    else:
        mood_score = 3

    # CLEANED: Removed parenthesis and explanation from info box
    st.info(f"Vibe Selected: {mood_choice.split('(')[0].strip()}")


with col2:
    # CLEANED: NO EMOJIS IN HEADER
    st.markdown("### Scene Location")

    location_map = {
        # CLEANED: Removed all Emojis from location options
        "Home": "Home",
        "Commute": "Commute",
        "Work": "Work",
        "Study": "Study",
        "Park": "Park",
    }

    location_label = st.radio(
        label="Where are you listening?",
        options=list(location_map.keys()),
        index=0
    )
    location_key = location_map[location_label]

    st.info(f"Scene Selected: {location_key}")


st.markdown("---")

# --- Music Recommendation Button ---
if st.button("GET VIBE"):

    recommended_genre = recommend_music(mood_score, location_key)

    if recommended_genre in MUSIC_DATA and MUSIC_DATA[recommended_genre]:
        track_url = random.choice(MUSIC_DATA[recommended_genre])

        # CLEANED: Removed Emoji from subheader
        st.subheader(f"Recommended: {recommended_genre}")

        iframe_html = f"""
            <iframe
                src="{track_url}"
                width="100%"
                height="350"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
            </iframe>
        """
        st.markdown(iframe_html, unsafe_allow_html=True)
    else:
        st.error(f"Error: No tracks found for {recommended_genre}.")

st.markdown("---")
st.markdown("From Hakowxy")