# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149697yabGWNdR7gY-aZzjDnVePoUKiA0
"""

import streamlit as st
import random

# --- 1. music data (unchanged) ---
MUSIC_DATA = {
    "city pop": [
        "https://www.youtube.com/embed/TBLZSXwfjbE",
        "https://www.youtube.com/embed/p9dRg8yQ2DY",
    ],
    "jazz hiphop": [
        "https://www.youtube.com/embed/dtVwR4uMnfg",
        "https://www.youtube.com/embed/OIvGy0wM5_s",
    ],
    "study focus": [
        "https://www.youtube.com/embed/219beSEfbqA",
        "https://www.youtube.com/embed/_Q8Ih2SW-TE",
    ],
    "ambient jazz": [
        "https://www.youtube.com/embed/CfPxlb8-ZQ0",
        "https://www.youtube.com/embed/o26qoCYLdS8",
    ]
}

# --- 2. core recommendation logic (unchanged) ---
def recommend_music(mood_score, location):

    if mood_score >= 8:
        genre = "city pop"
    elif mood_score >= 5:
        genre = "jazz hiphop"
    else:
        genre = "ambient jazz"

    if location in ["commute"]:
        genre = "city pop" if mood_score >= 5 else "jazz hiphop"
    elif location in ["study", "work"]:
        genre = "study focus" if mood_score >= 6 else "jazz hiphop"
    elif location == "park":
        genre = "city pop" if mood_score >= 6 else "jazz hiphop"
    elif location == "home":
        genre = "ambient jazz" if mood_score < 6 else "jazz hiphop"

    return genre

# --- 3. streamlit ui (pure python for ui/style) ---

st.set_page_config(page_title="kawaii jukebox", layout="wide")

# --- custom css for kawaii minimalism & color correction ---
st.markdown("""
    <style>
    /* 1. font and background */
    @import url('https://fonts.googleapis.com/css2?family=Indie+Flower&family=Gochi+Hand&display=swap');

    .stApp {
        background-color: #284d3c;
        color: #FFFFFF;
        font-family: 'Indie Flower', 'Gochi Hand', cursive;
        font-size: 1.4em;
        text-transform: lowercase;
    }
    h1, h2, h3 {
        color: #FF69B4;
        font-family: 'Indie Flower', 'Gochi Hand', cursive;
        font-weight: 900;
        text-shadow: 2px 2px 3px rgba(0, 0, 0, 0.6);
        text-transform: lowercase;
    }

    /* 2. custom radio button (VISUAL CHECKMARK SIMULATION) */

    [data-testid="stForm"] label, [data-testid="stRadio"] label {
        color: #FFFFFF;
        text-transform: lowercase;
    }

    /* Target the dot element */
    [data-testid="stRadio"] input[type="radio"] + div::before {
        border-radius: 0% !important; /* *** KEY CHANGE: Change from circle (50%) to square (0%) *** */
        width: 18px; /* Make it a clear square */
        height: 18px;
    }

    /* Checkmark dot when SELECTED (The pink square) */
    [data-testid="stRadio"] input[type="radio"]:checked + div::before {
        background-color: #FF69B4 !important; /* Hot Pink Square */
        border: 4px solid #FFFFFF !important; /* White Border */
    }
    /* Checkmark dot when NOT selected (The white square) */
    [data-testid="stRadio"] input[type="radio"] + div::before {
        background-color: #FFFFFF !important; /* White dot */
        border: 2px solid #FF69B4 !important; /* Hot Pink border */
    }

    /* 3. button style (fixed: cream/beige) */
    .stButton>button {
        background-color: #F5F5DC;
        color: #FF69B4;
        border: 3px solid #FF69B4;
        font-weight: 700;
        border-radius: 12px;
        font-family: 'Indie Flower', 'Gochi Hand', cursive;
        font-size: 1.4em;
        text-transform: lowercase;
    }
    .stButton>button:hover {
        background-color: #f0f0c9;
    }

    /* 4. slider style (knob) */
    .stSlider [data-testid="stThumbValue"] {
        background-color: #FF69B4;
        border: 2px solid #FFFFFF;
    }
    .stSlider [data-testid="stTrack"] {
        background: linear-gradient(to right, #FFFFFF, #FF69B4);
    }

    /* 5. snowfall styles (cute christmas vibe) */
    @keyframes snowfall {
        0% {top: -10%;}
        100% {top: 100%;}
    }
    .snowflake {
        color: #FFFFFF;
        font-size: 1.2em;
        position: fixed;
        z-index: 9999;
        user-select: none;
        pointer-events: none;
        animation-name: snowfall;
        animation-timing-function: linear;
        animation-iteration-count: infinite;
    }
    .snowflake:nth-child(1) { left: 5%; font-size: 1.5em; animation-duration: 10s; animation-delay: 0s; }
    .snowflake:nth-child(2) { left: 15%; font-size: 1.0em; animation-duration: 15s; animation-delay: 2s; }
    .snowflake:nth-child(3) { left: 25%; font-size: 1.8em; animation-duration: 12s; animation-delay: 4s; }
    .snowflake:nth-child(4) { left: 40%; font-size: 1.3em; animation-duration: 18s; animation-delay: 6s; }
    .snowflake:nth-child(5) { left: 60%; font-size: 1.6em; animation-duration: 11s; animation-delay: 8s; }
    .snowflake:nth-child(6) { left: 80%; font-size: 1.1em; animation-duration: 16s; animation-delay: 10s; }
    </style>
""", unsafe_allow_html=True)

# --- snowfall html ---
st.markdown("""
    <div class="snowflake">💖</div>
    <div class="snowflake">⭐</div>
    <div class="snowflake">🎄</div>
    <div class="snowflake">🎀</div>
    <div class="snowflake">❄️</div>
    <div class="snowflake">⭐</div>
""", unsafe_allow_html=True)

# --- app title ---
st.title("mood jukebox")
st.markdown("---")


# --- ui controls (creative input) ---
col1, col2 = st.columns(2)

with col1:
    # --- creative interaction: the knob/dial effect ---
    st.markdown("### set your mood dial")

    mood_score = st.slider(
        label="turn the knob: 1 (cozy) to 10 (sparkly)",
        min_value=1,
        max_value=10,
        value=6
    )

    # provide visual feedback based on the knob position
    if mood_score >= 8:
        # CLEANED: Only core description retained
        vibe_text = "sparkly"
    elif mood_score >= 5:
        # CLEANED: Only core description retained
        vibe_text = "calm"
    else:
        # CLEANED: Only core description retained
        vibe_text = "cozy"

    # st.info removed entirely
    st.markdown(f"**current vibe:** {vibe_text}")


with col2:
    st.markdown("### scene location")

    location_map = {
        "home": "home",
        "commute": "commute",
        "work": "work",
        "study": "study",
        "park": "park",
    }

    location_label = st.radio(
        label="where are you listening?",
        options=list(location_map.keys()),
        index=0
    )
    location_key = location_map[location_label]

    # st.info removed entirely
    st.markdown(f"**scene selected:** {location_key}")


st.markdown("---")

# --- music recommendation button ---
if st.button("get vibe"):

    recommended_genre = recommend_music(mood_score, location_key)

    if recommended_genre in MUSIC_DATA and MUSIC_DATA[recommended_genre]:
        track_url = random.choice(MUSIC_DATA[recommended_genre])

        st.subheader(f"recommended: {recommended_genre} 🎶")

        iframe_html = f"""
            <iframe
                src="{track_url}"
                width="100%"
                height="350"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
            </iframe>
        """
        st.markdown(iframe_html, unsafe_allow_html=True)
    else:
        st.error(f"error: no tracks found for {recommended_genre}.")

st.markdown("---")
st.markdown("from hakowxy")